[basefeeds]
MiamiDadeTransit = 'https://www.miamidade.gov/transit/WebServices/'
MiamiDadeTransitVerbose = 'https://www.miamidade.gov/transit/mobile/xml/'
Brightline = 'https://www.gobrightline.com/api/'
BrightlineSystem = 'https://luxapi.verbinteractive.com/api/'
TSOMobile = 'https://rest.tsoapi.com/'
CoralGablesETA = 'http://cgpublic.etaspot.net/service.php'
TriRailETA = 'http://trirailpublic.etaspot.net/service.php'

[GTFSPlaces]
MiamiDadeTransit = 'https://www.miamidade.gov/transit/googletransit/current/google_transit.zip'
SFRTATriRail = 'https://www.tri-rail.com/GTDF/Current/google_transit.zip'
Brightline = 'https://gobrightline.com/gtfs/gtfs.zip'

[[TSOMobile]]
name = 'Miami Beach'
id = 22844
  # Left is TSO Route ID - Right is Miami-Dade Transit GTFS Route ID
  [TSOMobile.routeMap]
  '73772' = '18786' # Collins Express
  '72486' = '18787' # Mid Beach Loop
  '40756' = '16894' # North Beach Loop
  '85862' = '19935' # SOBE Loop A (Clockwise)
  '85863' = '19935' # SOBE Loop B (Counter-Clockwise)
  '85864' = '19935' # SOBE Loop via 11th St

  [TSOMobile.headsigns]
  '73772' = 'Collins Link'
  '72486' = 'Middle Beach'
  '40756' = 'North Beach'
  '85862' = 'SOBE Loop A'
  '85863' = 'SOBE Loop B'
  '85864' = 'SOBE Loop via 11th St'

[[TSOMobile]]
name = 'Miami'
alias = 'Miami Trolley'
id = 21241
  [TSOMobile.routeMap]
  '71269' = '16889' # Allapattah
  '71276' = '16885' # Biscayne
  '71304' = '16886' # Brickell
  # '95029' No coconut grove route
  '71322' = '16887' # Coral Way
  # '94590' No flagami
  '71342' = '16891' # Health District
  # '88467' No little haiti 
  # '75187' No little havana
  # '97325' No cross bay express
  '71344' = '16890' # Overtown
  '71345' = '16892' # Stadium (circulates Health District to Marlins Park)

  [TSOMobile.headsigns]
  '71269' = 'Allapattah'
  '71276' = 'Biscayne'
  '101446' = 'Biscayne (Detour)' # (remove after 4/21/19)
  '71304' = 'Brickell'
  '95029' = 'Coconut Grove'
  '71322' = 'Coral Way'
  '94590' = 'Flagami'
  '71342' = 'Health District'
  '88467' = 'Little Haiti'
  '75187' = 'Little Havana'
  '97325' = 'Cross Bay Express'
  '71344' = 'Overtown'
  '71345' = 'Stadium'

[[TSOMobile]]
name = 'Doral'
alias = 'Doral Trolley'
id = 2500
  [TSOMobile.routeMap]
  '35929' = '16895' # Route 1
  '95835' = '16896' # Route 2
  '95836' = '16897' # Route 3

  [TSOMobile.headsigns]
  '35929' = 'Route 1'
  '95835' = 'Route 2'
  '95836' = 'Route 3'

[[TSOMobile]]
name = 'North Miami'
alias = 'NOMI Express'
id = 24600
  [TSOMobile.routeMap]
  # '91301' Blue
  # '91281' Green
  '91340' = '17792' # Orange
  # '91398' Red

  [TSOMobile.headsigns]
  '91301' = 'Blue'
  '91281' = 'Green'
  '91340' = 'Orange'
  '91398' = 'Red'

[[TSOMobile]]
name = 'Aventura'
alias = 'Aventura Express Shuttle Bus'
id = 26082
  [TSOMobile.routeMap]
  # No links available w/ Miami-Dade Transit GTFS
  [TSOMobile.headsigns]

[[TSOMobile]]
name = 'Sunny Isles Beach'
alias = 'Sunny Isles Beach Shuttle'
id = 31344
  [TSOMobile.routeMap]

  [TSOMobile.headsigns]

[[TSOMobile]]
name = 'North Miami Beach'
alias = 'NMB Line'
id = 31934
  [TSOMobile.routeMap]
  '76332' = '18112' # Route A (GTFS lists this as 'B-Line' even though it's A)

  [TSOMobile.headsigns]
  '76332' = 'Route A'
  '76334' = 'Route B'
  '76338' = 'Route C'

[[TSOMobile]]
name = 'Pinecrest'
alias = 'Pinecrest People Mover'
id = 24560
  [TSOMobile.routeMap]

  [TSOMobile.headsigns]

[[TSOMobile]]
name = 'Bal Harbour'
alias = 'Bal Harbour Express Shuttle'
id = 34323
  [TSOMobile.routeMap]
  '69516' = '17796'
  [TSOMobile.headsigns]
  '69516' = 'Bal Harbour'

[[TSOMobile]]
name = 'Palmetto Bay'
alias = 'Village of Palmetto Bay IBUS'
id = 49454
  [TSOMobile.routeMap]
  '95974' = '20408'
  [TSOMobile.headsigns]
  # '95974' Determined by trips.txt, this is a normal bus

[[TSOMobile]]
name = 'South Miami'
id = 34423
  [TSOMobile.routeMap]

  [TSOMobile.headsigns]

[[TSOMobile]]
name = 'Miami-Dade Transit'
alias = '@MiamiDadeTransit' # Special
id = 30109
  # These routes may be also tracked by MDT, be wary of data overlap.
  # Buses here have names like "Bus 423" which corresponds
  # to "LSF423" from Miami-Dade Transit XML Feeds. In other cases,
  # bus names might be listed as only "3779", and appear as "AT3779"
  # with Miami-Dade Transit's own AVL data.
  [TSOMobile.routeMap]
  '83299' = '21396' # Sweetwater
  '83294' = '21395' # Overtown
  '92084' = '21394' # Skylake
  '94171' = '21380' # Biscayne Gardens
  '81711' = '21404' # Brownsville
  '98191' = '21402' # Princeton
  '81712' = '21409' # North Pointe
  '81709' = '21448' # Westchester
  '92085' = '21397' # Bunche Park
  '82479' = '21358' # 1: SO.MIAMI HTS-PERRINE VIA SOUTHLAND
  '82499' = '21412' # 29: HIALEAH TRIANGLE-MIAMI LAKES
  '99843' = '21425' # 35: MDC KENDALL-FLA.CITY VIA CUTLER BAY
  '99847' = '21425' # 35A: MDC KENDALL-FLA.CITY VIA CUTLER BAY
  '81708' = '21432' # 46: LIBERTY CITY CONNECTION
  '92086' = '21437' # 56: CHILDREN HOSP TO 162 AVE VIA 56 ST
  '92092' = '21441' # 71: DOLPHIN MALL-MDC KEND.VIA 107/112AV
  '92090' = '21442' # 72: SO.MIAMI-BENT TREE/162AV VIA 72 ST
  '92089' = '21442' # 72A: SO.MIAMI-BENT TREE/162AV VIA 72 ST
  '81710' = '21360' # 101: A-VIA VENETIAN CAUSEWAY
  '98748' = '21371' # 115: MID-NORTH-BEACH CONNECTION
  '83276' = '21389' # 202: LITTLE HAITI CONNECTION
  '83339' = '21401' # 246: NIGHT OWL
  '83303' = '21405' # 267: LUDLAM LIMITED
  '83348' = '21407' # 272: SUNSET KAT
  '59434' = '21417' # 301: DADE/MONROE EXPRESS
  '59545' = '21418' # 302: CARD SOUND EXPRESS
  '83359' = '21424' # 344: MDC HOMESTEAD TO FLA CITY

  [TSOMobile.headsigns]
  '83299' = 'Sweetwater Trolley'
  '83294' = 'Overtown Circulator'
  '92084' = 'Skylake Circulator'
  '94171' = 'Biscayne Gardens Circulator'
  '81711' = 'Brownsville Circulator'
  '98191' = 'Princeton Circulator'
  '81712' = 'North Pointe Circulator'
  '81709' = 'Westchester Circulator'
  '92085' = 'Bunche Park Circulator'
